In [1]:
import json
from pathlib import Path
import pandas as pd

# --- paths ---
fp1 = Path("dataset_reddit-scraper_2026-03-24_00-00-33-244.json")
fp2 = Path("dataset_reddit-scraper_2026-03-24_18-29-51-236.json")

# --- load ---
with open(fp1, "r", encoding="utf-8") as f:
    data1 = json.load(f)

with open(fp2, "r", encoding="utf-8") as f:
    data2 = json.load(f)

df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)

print("file 1 rows:", len(df1))
print("file 2 rows:", len(df2))
print()

print("file 1 columns:")
print(sorted(df1.columns.tolist()))
print()
print("file 2 columns:")
print(sorted(df2.columns.tolist()))

file 1 rows: 776
file 2 rows: 515

file 1 columns:
['age_seconds', 'archived', 'author', 'comment_id', 'comments_per_hour', 'controversiality', 'created_utc_iso', 'created_utc_ts', 'depth', 'discussion_ratio', 'distinguished', 'domain', 'edited', 'engagement_level', 'estimated_downvotes', 'estimated_upvotes', 'gilded', 'has_media', 'has_question_mark', 'has_url', 'is_controversial', 'is_original_content', 'is_self', 'is_submitter', 'is_video', 'link_flair_text', 'listing_page', 'listing_rank', 'listing_sort', 'listing_timeframe', 'locked', 'matched_domain_targets', 'matched_domains', 'matched_search_queries', 'matched_search_targets', 'missing_direct_replies', 'num_comments', 'num_crossposts', 'over_18', 'parent_id', 'parent_type', 'permalink', 'post_id', 'record_type', 'reply_count_direct', 'reply_count_total', 'run_id', 'score', 'score_per_hour', 'scraped_at_iso', 'scraped_at_ts', 'source', 'spoiler', 'stickied', 'subreddit', 'tag', 'task_id', 'text', 'thumbnail', 'title', 'total_awards_received', 'total_votes', 'upvote_ratio', 'url']

file 2 columns:
['age_seconds', 'archived', 'author', 'comment_id', 'comments_per_hour', 'controversiality', 'created_utc_iso', 'created_utc_ts', 'depth', 'discussion_ratio', 'distinguished', 'domain', 'edited', 'engagement_level', 'estimated_downvotes', 'estimated_upvotes', 'gilded', 'has_media', 'has_question_mark', 'has_url', 'is_controversial', 'is_original_content', 'is_self', 'is_submitter', 'is_video', 'link_flair_text', 'listing_page', 'listing_rank', 'listing_sort', 'listing_timeframe', 'locked', 'matched_domain_targets', 'matched_domains', 'matched_search_queries', 'matched_search_targets', 'missing_direct_replies', 'num_comments', 'num_crossposts', 'over_18', 'parent_id', 'parent_type', 'permalink', 'post_id', 'record_type', 'reply_count_direct', 'reply_count_total', 'run_id', 'score', 'score_per_hour', 'scraped_at_iso', 'scraped_at_ts', 'source', 'spoiler', 'stickied', 'subreddit', 'tag', 'task_id', 'text', 'thumbnail', 'title', 'total_awards_received', 'total_votes', 'upvote_ratio', 'url']

In [4]:
df1.head()

,record_type,source,post_id,subreddit,title,text,author,url,permalink,domain,...,comment_id,parent_type,parent_id,depth,controversiality,is_submitter,reply_count_direct,reply_count_total,missing_direct_replies,source_file
0,post,reddit,1s1vxim,icecoast,Sunday River Conditions 3/23,Only skied for the last hour today. Groomed/pa...,sage89,https://i.redd.it/fxlflfg9gvqg1.jpeg,https://www.reddit.com/r/icecoast/comments/1s1...,i.redd.it,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,dataset_reddit-scraper_2026-03-24_00-00-33-244...
1,post,reddit,1s1f240,icecoast,Sugarloaf and Sunday river worth the 6 hour dr...,Will sugarloaf open more terrain by Tuesday? I...,astrobrite_,https://old.reddit.com/r/icecoast/comments/1s1...,https://www.reddit.com/r/icecoast/comments/1s1...,self.icecoast,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,dataset_reddit-scraper_2026-03-24_00-00-33-244...
2,post,reddit,1s11ob9,icecoast,Sunday River won the day,Tons of fresh snow. Tons of terrain reopened.\...,Important_Repeat_806,https://v.redd.it/jswqssauroqg1,https://www.reddit.com/r/icecoast/comments/1s1...,v.redd.it,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,dataset_reddit-scraper_2026-03-24_00-00-33-244...
3,post,reddit,1s05x7t,icecoast,Sunday rivah conditions 3/21,"was great from 8-11am, spots felt deeper than ...",Longjumping-Date-181,https://i.redd.it/xtj7zap4fhqg1.jpeg,https://www.reddit.com/r/icecoast/comments/1s0...,i.redd.it,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,dataset_reddit-scraper_2026-03-24_00-00-33-244...
4,post,reddit,1rxyuhn,icecoast,Mad River Glen,I have one ticket for Mad River Glen that can ...,Wonderful-Court-6395,https://old.reddit.com/r/icecoast/comments/1rx...,https://www.reddit.com/r/icecoast/comments/1rx...,self.icecoast,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,dataset_reddit-scraper_2026-03-24_00-00-33-244...

In [7]:
df2[df2['record_type']=='comment'].head()

,record_type,source,post_id,subreddit,title,text,author,url,permalink,domain,...,comment_id,parent_type,parent_id,depth,controversiality,is_submitter,reply_count_direct,reply_count_total,missing_direct_replies,source_file
44,comment,reddit,1s2hkj6,icecoast,NaN,Lift #9 should be open even if #11 closes. It...,augustcurrents151,NaN,https://www.reddit.com/r/icecoast/comments/1s2...,NaN,...,oc8j1j2,post,1s2hkj6,0.0,0.0,False,0.0,0.0,0.0,dataset_reddit-scraper_2026-03-24_18-29-51-236...
45,comment,reddit,1s2hkd3,icecoast,NaN,Everywhere will be icy this weekend in the NE....,negative-nelly,NaN,https://www.reddit.com/r/icecoast/comments/1s2...,NaN,...,oc82fp5,post,1s2hkd3,0.0,0.0,False,0.0,0.0,0.0,dataset_reddit-scraper_2026-03-24_18-29-51-236...
46,comment,reddit,1s2hkd3,icecoast,NaN,lift 11 will most likely run,DoubleFroggin,NaN,https://www.reddit.com/r/icecoast/comments/1s2...,NaN,...,oc8ncqy,post,1s2hkd3,0.0,0.0,False,0.0,0.0,0.0,dataset_reddit-scraper_2026-03-24_18-29-51-236...
47,comment,reddit,1s2dqbl,icecoast,NaN,Sunday River appears to be the place to be in ...,auddy5000,NaN,https://www.reddit.com/r/icecoast/comments/1s2...,NaN,...,oc7n7lm,post,1s2dqbl,0.0,0.0,False,0.0,0.0,0.0,dataset_reddit-scraper_2026-03-24_18-29-51-236...
48,comment,reddit,1s2dqbl,icecoast,NaN,First 4 laps today down groomers 10/10 2 inch ...,sage89,NaN,https://www.reddit.com/r/icecoast/comments/1s2...,NaN,...,oc7et5q,post,1s2dqbl,0.0,0.0,False,1.0,2.0,0.0,dataset_reddit-scraper_2026-03-24_18-29-51-236...

Check for duplicates in between extractions

In [2]:
import json
from pathlib import Path
import pandas as pd

fp1 = Path("dataset_reddit-scraper_2026-03-24_00-00-33-244.json")
fp2 = Path("dataset_reddit-scraper_2026-03-24_18-29-51-236.json")

with open(fp1, "r", encoding="utf-8") as f:
    data1 = json.load(f)

with open(fp2, "r", encoding="utf-8") as f:
    data2 = json.load(f)

df1 = pd.DataFrame(data1).copy()
df2 = pd.DataFrame(data2).copy()

df1["source_file"] = fp1.name
df2["source_file"] = fp2.name

# Keep only rows that actually have a comment_id
c1 = df1[df1["comment_id"].notna()].copy()
c2 = df2[df2["comment_id"].notna()].copy()

print("file 1 comment rows:", len(c1))
print("file 2 comment rows:", len(c2))
print("file 1 unique comment_id:", c1["comment_id"].nunique())
print("file 2 unique comment_id:", c2["comment_id"].nunique())

# Overlap of comment_ids across files
comment_ids_1 = set(c1["comment_id"])
comment_ids_2 = set(c2["comment_id"])
overlap_comment_ids = comment_ids_1 & comment_ids_2

print("overlapping comment_ids across files:", len(overlap_comment_ids))
print("sample overlapping comment_ids:", list(sorted(overlap_comment_ids))[:20])

file 1 comment rows: 728
file 2 comment rows: 471
file 1 unique comment_id: 728
file 2 unique comment_id: 471
overlapping comment_ids across files: 445
sample overlapping comment_ids: ['o6twcs9', 'o6wmaoe', 'o6ysp2i', 'o6ywhmy', 'o6yx7i6', 'o6z0a9w', 'o6z3o0z', 'o6z5wp2', 'o7cgsik', 'o7d2ktm', 'o7daegb', 'o7ds49p', 'o7ebg42', 'o7elj8c', 'o7ss1ww', 'o7ss35d', 'o7ss6u4', 'o7vbxy9', 'o7vj4gr', 'o7xjnkx']

In [3]:
overlap_comments = pd.concat(
    [
        c1[c1["comment_id"].isin(overlap_comment_ids)],
        c2[c2["comment_id"].isin(overlap_comment_ids)],
    ],
    ignore_index=True
)

overlap_comments = overlap_comments.sort_values(["comment_id", "source_file"]).reset_index(drop=True)

cols_to_show = [
    "source_file",
    "record_type",
    "comment_id",
    "post_id",
    "parent_id",
    "parent_type",
    "subreddit",
    "author",
    "created_utc_iso",
    "title",
    "text",
    "permalink",
]

display(overlap_comments[cols_to_show].head(50))

,source_file,record_type,comment_id,post_id,parent_id,parent_type,subreddit,author,created_utc_iso,title,text,permalink
0,dataset_reddit-scraper_2026-03-24_00-00-33-244...,comment,o6twcs9,1razohr,1razohr,post,icecoast,gstormcrow80,2026-02-22T20:00:22Z,NaN,The only reason no one has commented is becaus...,https://www.reddit.com/r/icecoast/comments/1ra...
1,dataset_reddit-scraper_2026-03-24_18-29-51-236...,comment,o6twcs9,1razohr,1razohr,post,icecoast,gstormcrow80,2026-02-22T20:00:22Z,NaN,The only reason no one has commented is becaus...,https://www.reddit.com/r/icecoast/comments/1ra...
2,dataset_reddit-scraper_2026-03-24_00-00-33-244...,comment,o6wmaoe,1razohr,1razohr,post,icecoast,SimilarRegret9731,2026-02-23T05:35:37Z,NaN,Okemo was fire,https://www.reddit.com/r/icecoast/comments/1ra...
3,dataset_reddit-scraper_2026-03-24_18-29-51-236...,comment,o6wmaoe,1razohr,1razohr,post,icecoast,SimilarRegret9731,2026-02-23T05:35:37Z,NaN,Okemo was fire,https://www.reddit.com/r/icecoast/comments/1ra...
4,dataset_reddit-scraper_2026-03-24_00-00-33-244...,comment,o6ysp2i,1rckiqs,1rckiqs,post,icecoast,Traditional_Owl12,2026-02-23T15:36:06Z,NaN,Just pick the mountain you’re most interested ...,https://www.reddit.com/r/icecoast/comments/1rc...
5,dataset_reddit-scraper_2026-03-24_18-29-51-236...,comment,o6ysp2i,1rckiqs,1rckiqs,post,icecoast,Traditional_Owl12,2026-02-23T15:36:06Z,NaN,Just pick the mountain you’re most interested ...,https://www.reddit.com/r/icecoast/comments/1rc...
6,dataset_reddit-scraper_2026-03-24_00-00-33-244...,comment,o6ywhmy,1rckiqs,1rckiqs,post,icecoast,teucer_,2026-02-23T15:54:03Z,NaN,"As a questionable upside, if you choose Killin...",https://www.reddit.com/r/icecoast/comments/1rc...
7,dataset_reddit-scraper_2026-03-24_18-29-51-236...,comment,o6ywhmy,1rckiqs,1rckiqs,post,icecoast,teucer_,2026-02-23T15:54:03Z,NaN,"As a questionable upside, if you choose Killin...",https://www.reddit.com/r/icecoast/comments/1rc...
8,dataset_reddit-scraper_2026-03-24_00-00-33-244...,comment,o6yx7i6,1rckiqs,1rckiqs,post,icecoast,Acton_up,2026-02-23T15:57:24Z,NaN,Just got back from a week plus at Sugarbush wi...,https://www.reddit.com/r/icecoast/comments/1rc...
9,dataset_reddit-scraper_2026-03-24_18-29-51-236...,comment,o6yx7i6,1rckiqs,1rckiqs,post,icecoast,Acton_up,2026-02-23T15:57:24Z,NaN,Just got back from a week plus at Sugarbush wi...,https://www.reddit.com/r/icecoast/comments/1rc...
10,dataset_reddit-scraper_2026-03-24_00-00-33-244...,comment,o6z0a9w,1rckiqs,1rckiqs,post,icecoast,Potential_Leg4423,2026-02-23T16:11:44Z,NaN,[March 2026 Outlook](https://www.google.com/ac...,https://www.reddit.com/r/icecoast/comments/1rc...
11,dataset_reddit-scraper_2026-03-24_18-29-51-236...,comment,o6z0a9w,1rckiqs,1rckiqs,post,icecoast,Potential_Leg4423,2026-02-23T16:11:44Z,NaN,[March 2026 Outlook](https://www.google.com/ac...,https://www.reddit.com/r/icecoast/comments/1rc...
12,dataset_reddit-scraper_2026-03-24_00-00-33-244...,comment,o6z3o0z,1rckiqs,1rckiqs,post,icecoast,___this_guy,2026-02-23T16:27:26Z,NaN,March crowds are way less because sports start...,https://www.reddit.com/r/icecoast/comments/1rc...
13,dataset_reddit-scraper_2026-03-24_18-29-51-236...,comment,o6z3o0z,1rckiqs,1rckiqs,post,icecoast,___this_guy,2026-02-23T16:27:26Z,NaN,March crowds are way less because sports start...,https://www.reddit.com/r/icecoast/comments/1rc...
14,dataset_reddit-scraper_2026-03-24_00-00-33-244...,comment,o6z5wp2,1rckiqs,1rckiqs,post,icecoast,ShaveICE23,2026-02-23T16:37:46Z,NaN,Bush 💯,https://www.reddit.com/r/icecoast/comments/1rc...
15,dataset_reddit-scraper_2026-03-24_18-29-51-236...,comment,o6z5wp2,1rckiqs,1rckiqs,post,icecoast,ShaveICE23,2026-02-23T16:37:46Z,NaN,Bush 💯,https://www.reddit.com/r/icecoast/comments/1rc...
16,dataset_reddit-scraper_2026-03-24_00-00-33-244...,comment,o7cgsik,1reh0cg,1reh0cg,post,icecoast,next_baguette,2026-02-25T16:01:53Z,NaN,Saturday should still be fun. The sun and temp...,https://www.reddit.com/r/icecoast/comments/1re...
17,dataset_reddit-scraper_2026-03-24_18-29-51-236...,comment,o7cgsik,1reh0cg,1reh0cg,post,icecoast,next_baguette,2026-02-25T16:01:53Z,NaN,Saturday should still be fun. The sun and temp...,https://www.reddit.com/r/icecoast/comments/1re...
18,dataset_reddit-scraper_2026-03-24_00-00-33-244...,comment,o7d2ktm,1reh0cg,1reh0cg,post,icecoast,Competitive-Pie-Eate,2026-02-25T17:41:28Z,NaN,Killington is larger and haze more terrain and...,https://www.reddit.com/r/icecoast/comments/1re...
19,dataset_reddit-scraper_2026-03-24_18-29-51-236...,comment,o7d2ktm,1reh0cg,1reh0cg,post,icecoast,Competitive-Pie-Eate,2026-02-25T17:41:28Z,NaN,Killington is larger and haze more terrain and...,https://www.reddit.com/r/icecoast/comments/1re...
20,dataset_reddit-scraper_2026-03-24_00-00-33-244...,comment,o7daegb,1reh0cg,o7d2ktm,comment,icecoast,ArmKnown63,2026-02-25T18:16:20Z,NaN,Pico was phenominal on Monday.,https://www.reddit.com/r/icecoast/comments/1re...
21,dataset_reddit-scraper_2026-03-24_18-29-51-236...,comment,o7daegb,1reh0cg,o7d2ktm,comment,icecoast,ArmKnown63,2026-02-25T18:16:20Z,NaN,Pico was phenominal on Monday.,https://www.reddit.com/r/icecoast/comments/1re...
22,dataset_reddit-scraper_2026-03-24_00-00-33-244...,comment,o7ds49p,1reh0cg,o7d2ktm,comment,icecoast,PopularSubs,2026-02-25T19:37:02Z,NaN,Is there anywhere I hang out with a medium siz...,https://www.reddit.com/r/icecoast/comments/1re...
23,dataset_reddit-scraper_2026-03-24_18-29-51-236...,comment,o7ds49p,1reh0cg,o7d2ktm,comment,icecoast,PopularSubs,2026-02-25T19:37:02Z,NaN,Is there anywhere I hang out with a medium siz...,https://www.reddit.com/r/icecoast/comments/1re...
24,dataset_reddit-scraper_2026-03-24_00-00-33-244...,comment,o7ebg42,1reh0cg,o7cgsik,comment,icecoast,GoodShepherd3264,2026-02-25T21:07:07Z,NaN,Second this. Saturday should be great. Sunday ...,https://www.reddit.com/r/icecoast/comments/1re...
25,dataset_reddit-scraper_2026-03-24_18-29-51-236...,comment,o7ebg42,1reh0cg,o7cgsik,comment,icecoast,GoodShepherd3264,2026-02-25T21:07:07Z,NaN,Second this. Saturday should be great. Sunday ...,https://www.reddit.com/r/icecoast/comments/1re...
26,dataset_reddit-scraper_2026-03-24_00-00-33-244...,comment,o7elj8c,1reh0cg,1reh0cg,post,icecoast,Otherwise-Dig-5094,2026-02-25T21:53:48Z,NaN,Belleayre is sold out for Saturday if that mat...,https://www.reddit.com/r/icecoast/comments/1re...
27,dataset_reddit-scraper_2026-03-24_18-29-51-236...,comment,o7elj8c,1reh0cg,1reh0cg,post,icecoast,Otherwise-Dig-5094,2026-02-25T21:53:48Z,NaN,Belleayre is sold out for Saturday if that mat...,https://www.reddit.com/r/icecoast/comments/1re...
28,dataset_reddit-scraper_2026-03-24_00-00-33-244...,comment,o7ss1ww,1rckiqs,o6z5wp2,comment,icecoast,ClimbRave,2026-02-28T00:38:30Z,NaN,Yes. I second this,https://www.reddit.com/r/icecoast/comments/1rc...
29,dataset_reddit-scraper_2026-03-24_18-29-51-236...,comment,o7ss1ww,1rckiqs,o6z5wp2,comment,icecoast,ClimbRave,2026-02-28T00:38:30Z,NaN,Yes. I second this,https://www.reddit.com/r/icecoast/comments/1rc...
30,dataset_reddit-scraper_2026-03-24_00-00-33-244...,comment,o7ss35d,1rckiqs,1rckiqs,post,icecoast,ClimbRave,2026-02-28T00:38:42Z,NaN,Sugarbush fr,https://www.reddit.com/r/icecoast/comments/1rc...
31,dataset_reddit-scraper_2026-03-24_18-29-51-236...,comment,o7ss35d,1rckiqs,1rckiqs,post,icecoast,ClimbRave,2026-02-28T00:38:42Z,NaN,Sugarbush fr,https://www.reddit.com/r/icecoast/comments/1rc...
32,dataset_reddit-scraper_2026-03-24_00-00-33-244...,comment,o7ss6u4,1rckiqs,o6ywhmy,comment,icecoast,ClimbRave,2026-02-28T00:39:18Z,NaN,This is true. All hail Birdman 🦅,https://www.reddit.com/r/icecoast/comments/1rc...
33,dataset_reddit-scraper_2026-03-24_18-29-51-236...,comment,o7ss6u4,1rckiqs,o6ywhmy,comment,icecoast,ClimbRave,2026-02-28T00:39:18Z,NaN,This is true. All hail Birdman 🦅,https://www.reddit.com/r/icecoast/comments/1rc...
34,dataset_reddit-scraper_2026-03-24_00-00-33-244...,comment,o7vbxy9,1rgvm6i,1rgvm6i,post,icecoast,Reputation-Adorable,2026-02-28T12:35:15Z,NaN,"Jordan Bowl, the green groomer has some awesom...",https://www.reddit.com/r/icecoast/comments/1rg...
35,dataset_reddit-scraper_2026-03-24_18-29-51-236...,comment,o7vbxy9,1rgvm6i,1rgvm6i,post,icecoast,Reputation-Adorable,2026-02-28T12:35:15Z,NaN,"Jordan Bowl, the green groomer has some awesom...",https://www.reddit.com/r/icecoast/comments/1rg...
36,dataset_reddit-scraper_2026-03-24_00-00-33-244...,comment,o7vj4gr,1rgvm6i,o7vbxy9,comment,icecoast,YWFD,2026-02-28T13:24:59Z,NaN,I spent so much time in Blind Ambition a coupl...,https://www.reddit.com/r/icecoast/comments/1rg...
37,dataset_reddit-scraper_2026-03-24_18-29-51-236...,comment,o7vj4gr,1rgvm6i,o7vbxy9,comment,icecoast,YWFD,2026-02-28T13:24:59Z,NaN,I spent so much time in Blind Ambition a coupl...,https://www.reddit.com/r/icecoast/comments/1rg...
38,dataset_reddit-scraper_2026-03-24_00-00-33-244...,comment,o7xjnkx,1rhbsxl,1rhbsxl,post,icecoast,RTMaiorano,2026-02-28T19:44:26Z,NaN,Last Sunday / Monday we hit Waterville Sunday ...,https://www.reddit.com/r/icecoast/comments/1rh...
39,dataset_reddit-scraper_2026-03-24_18-29-51-236...,comment,o7xjnkx,1rhbsxl,1rhbsxl,post,icecoast,RTMaiorano,2026-02-28T19:44:26Z,NaN,Last Sunday / Monday we hit Waterville Sunday ...,https://www.reddit.com/r/icecoast/comments/1rh...
40,dataset_reddit-scraper_2026-03-24_00-00-33-244...,comment,o84gen4,1ri9rog,1ri9rog,post,icecoast,noob_tube03,2026-03-01T21:36:54Z,NaN,In theory you could walk there from the Jordon...,https://www.reddit.com/r/icecoast/comments/1ri...
41,dataset_reddit-scraper_2026-03-24_18-29-51-236...,comment,o84gen4,1ri9rog,1ri9rog,post,icecoast,noob_tube03,2026-03-01T21:36:54Z,NaN,In theory you could walk there from the Jordon...,https://www.reddit.com/r/icecoast/comments/1ri...
42,dataset_reddit-scraper_2026-03-24_00-00-33-244...,comment,o84gh74,1ri9rog,1ri9rog,post,icecoast,Carpay,2026-03-01T21:37:16Z,NaN,You can walk there,https://www.reddit.com/r/icecoast/comments/1ri...
43,dataset_reddit-scraper_2026-03-24_18-29-51-236...,comment,o84gh74,1ri9rog,1ri9rog,post,icecoast,Carpay,2026-03-01T21:37:16Z,NaN,You can walk there,https://www.reddit.com/r/icecoast/comments/1ri...
44,dataset_reddit-scraper_2026-03-24_00-00-33-244...,comment,o84gpwc,1ri9rog,o84gen4,comment,icecoast,imadearedditjst4this,2026-03-01T21:38:30Z,NaN,There is a free shuttle every 30 mins from the...,https://www.reddit.com/r/icecoast/comments/1ri...
45,dataset_reddit-scraper_2026-03-24_18-29-51-236...,comment,o84gpwc,1ri9rog,o84gen4,comment,icecoast,imadearedditjst4this,2026-03-01T21:38:30Z,NaN,There is a free shuttle every 30 mins from the...,https://www.reddit.com/r/icecoast/comments/1ri...
46,dataset_reddit-scraper_2026-03-24_00-00-33-244...,comment,o84h1oe,1ri9rog,o84gh74,comment,icecoast,imadearedditjst4this,2026-03-01T21:40:10Z,NaN,There is a free shuttle every 30 mins. It pick...,https://www.reddit.com/r/icecoast/comments/1ri...
47,dataset_reddit-scraper_2026-03-24_18-29-51-236...,comment,o84h1oe,1ri9rog,o84gh74,comment,icecoast,imadearedditjst4this,2026-03-01T21:40:10Z,NaN,There is a free shuttle every 30 mins. It pick...,https://www.reddit.com/r/icecoast/comments/1ri...
48,dataset_reddit-scraper_2026-03-24_00-00-33-244...,comment,o84he6i,1ri9rog,o84gen4,comment,icecoast,imadearedditjst4this,2026-03-01T21:41:57Z,NaN,https://preview.redd.it/5zurful07img1.jpeg?wid...,https://www.reddit.com/r/icecoast/comments/1ri...
49,dataset_reddit-scraper_2026-03-24_18-29-51-236...,comment,o84he6i,1ri9rog,o84gen4,comment,icecoast,imadearedditjst4this,2026-03-01T21:41:57Z,NaN,https://preview.redd.it/5zurful07img1.jpeg?wid...,https://www.reddit.com/r/icecoast/comments/1ri...

In [8]:
dup_comment_ids_df = pd.DataFrame(
    sorted(overlap_comment_ids),
    columns=["comment_id"]
)

display(dup_comment_ids_df.head(50))

   comment_id
0     o6twcs9
1     o6wmaoe
2     o6ysp2i
3     o6ywhmy
4     o6yx7i6
5     o6z0a9w
6     o6z3o0z
7     o6z5wp2
8     o7cgsik
9     o7d2ktm
10    o7daegb
11    o7ds49p
12    o7ebg42
13    o7elj8c
14    o7ss1ww
15    o7ss35d
16    o7ss6u4
17    o7vbxy9
18    o7vj4gr
19    o7xjnkx
20    o84gen4
21    o84gh74
22    o84gpwc
23    o84h1oe
24    o84he6i
25    o84hi7t
26    o84hnaa
27    o84i21h
28    o84khyt
29    o84kxpd
30    o84l1if
31    o84lubg
32    o84mnod
33    o84o4yg
34    o84ohv4
35    o84opkk
36    o84pm8d
37    o84t2ia
38    o84tdoa
39    o84wdka
40    o84xs6d
41    o84ynb9
42    o84zi3s
43    o84zn2i
44    o85jlm9
45    o85l81p
46    o85m0wv
47    o85qh4e
48    o85u5q3
49    o85vs0f

In [9]:
combined_comments = pd.concat([c1, c2], ignore_index=True)

dup_counts = (
    combined_comments[combined_comments["comment_id"].isin(overlap_comment_ids)]
    .groupby("comment_id", as_index=False)
    .size()
    .sort_values(["size", "comment_id"], ascending=[False, True])
)

display(dup_counts.head(50))

   comment_id  size
0     o6twcs9     2
1     o6wmaoe     2
2     o6ysp2i     2
3     o6ywhmy     2
4     o6yx7i6     2
5     o6z0a9w     2
6     o6z3o0z     2
7     o6z5wp2     2
8     o7cgsik     2
9     o7d2ktm     2
10    o7daegb     2
11    o7ds49p     2
12    o7ebg42     2
13    o7elj8c     2
14    o7ss1ww     2
15    o7ss35d     2
16    o7ss6u4     2
17    o7vbxy9     2
18    o7vj4gr     2
19    o7xjnkx     2
20    o84gen4     2
21    o84gh74     2
22    o84gpwc     2
23    o84h1oe     2
24    o84he6i     2
25    o84hi7t     2
26    o84hnaa     2
27    o84i21h     2
28    o84khyt     2
29    o84kxpd     2
30    o84l1if     2
31    o84lubg     2
32    o84mnod     2
33    o84o4yg     2
34    o84ohv4     2
35    o84opkk     2
36    o84pm8d     2
37    o84t2ia     2
38    o84tdoa     2
39    o84wdka     2
40    o84xs6d     2
41    o84ynb9     2
42    o84zi3s     2
43    o84zn2i     2
44    o85jlm9     2
45    o85l81p     2
46    o85m0wv     2
47    o85qh4e     2
48    o85u5q3     2
49    o85vs0f     2

Langchain Labeler creation

In [10]:
import json
from pathlib import Path
import pandas as pd

files = [
    Path("dataset_reddit-scraper_2026-03-24_00-00-33-244.json"),
    Path("dataset_reddit-scraper_2026-03-24_18-29-51-236.json"),
]

dfs = []
for fp in files:
    with open(fp, "r", encoding="utf-8") as f:
        data = json.load(f)
    df = pd.DataFrame(data)
    df["source_file"] = fp.name
    dfs.append(df)

reddit_raw = pd.concat(dfs, ignore_index=True)
print("combined rows:", len(reddit_raw))
reddit_raw.head()

combined rows: 1291

,record_type,source,post_id,subreddit,title,text,author,url,permalink,domain,...,comment_id,parent_type,parent_id,depth,controversiality,is_submitter,reply_count_direct,reply_count_total,missing_direct_replies,source_file
0,post,reddit,1s1vxim,icecoast,Sunday River Conditions 3/23,Only skied for the last hour today. Groomed/pa...,sage89,https://i.redd.it/fxlflfg9gvqg1.jpeg,https://www.reddit.com/r/icecoast/comments/1s1...,i.redd.it,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,dataset_reddit-scraper_2026-03-24_00-00-33-244...
1,post,reddit,1s1f240,icecoast,Sugarloaf and Sunday river worth the 6 hour dr...,Will sugarloaf open more terrain by Tuesday? I...,astrobrite_,https://old.reddit.com/r/icecoast/comments/1s1...,https://www.reddit.com/r/icecoast/comments/1s1...,self.icecoast,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,dataset_reddit-scraper_2026-03-24_00-00-33-244...
2,post,reddit,1s11ob9,icecoast,Sunday River won the day,Tons of fresh snow. Tons of terrain reopened.\...,Important_Repeat_806,https://v.redd.it/jswqssauroqg1,https://www.reddit.com/r/icecoast/comments/1s1...,v.redd.it,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,dataset_reddit-scraper_2026-03-24_00-00-33-244...
3,post,reddit,1s05x7t,icecoast,Sunday rivah conditions 3/21,"was great from 8-11am, spots felt deeper than ...",Longjumping-Date-181,https://i.redd.it/xtj7zap4fhqg1.jpeg,https://www.reddit.com/r/icecoast/comments/1s0...,i.redd.it,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,dataset_reddit-scraper_2026-03-24_00-00-33-244...
4,post,reddit,1rxyuhn,icecoast,Mad River Glen,I have one ticket for Mad River Glen that can ...,Wonderful-Court-6395,https://old.reddit.com/r/icecoast/comments/1rx...,https://www.reddit.com/r/icecoast/comments/1rx...,self.icecoast,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,dataset_reddit-scraper_2026-03-24_00-00-33-244...

Single attempt Loading

In [11]:
import json
from pathlib import Path
import pandas as pd

fp = Path("dataset_reddit-scraper_2026-03-24_18-29-51-236.json")

In [12]:
with open(fp, "r", encoding="utf-8") as f:
    data = json.load(f)

raw_df = pd.DataFrame(data).copy()
raw_df["source_file"] = fp.name

print("rows in batch:", len(raw_df))
print("record_type counts:")
print(raw_df["record_type"].value_counts(dropna=False))

rows in batch: 515
record_type counts:
record_type
comment    471
post        44
Name: count, dtype: int64

In [13]:
def build_source_item_key(row: pd.Series):
    post_id = row.get("post_id")
    comment_id = row.get("comment_id")

    if pd.notna(comment_id) and str(comment_id).strip() != "":
        return f"{post_id}_{comment_id}"

    if pd.notna(post_id) and str(post_id).strip() != "":
        return f"{post_id}_post"

    return None

raw_df["source_item_key"] = raw_df.apply(build_source_item_key, axis=1)

print("null source_item_key:", raw_df["source_item_key"].isna().sum())
raw_df[["record_type", "post_id", "comment_id", "source_item_key"]].head(10)

null source_item_key: 0

  record_type  post_id comment_id source_item_key
0        post  1s2hkj6        NaN    1s2hkj6_post
1        post  1s2hkd3        NaN    1s2hkd3_post
2        post  1s2dqbl        NaN    1s2dqbl_post
3        post  1s1vxim        NaN    1s1vxim_post
4        post  1s1f240        NaN    1s1f240_post
5        post  1s11ob9        NaN    1s11ob9_post
6        post  1s05x7t        NaN    1s05x7t_post
7        post  1rxyuhn        NaN    1rxyuhn_post
8        post  1rxlql4        NaN    1rxlql4_post
9        post  1rxi12h        NaN    1rxi12h_post

In [14]:
cols_to_keep = [
    "source_item_key",
    "post_id",
    "comment_id",
    "record_type",
    "subreddit",
    "author",
    "title",
    "text",
    "permalink",
    "url",
    "created_utc_iso",
    "scraped_at_iso",
    "parent_id",
    "parent_type",
    "source_file",
]

reddit_df = raw_df[cols_to_keep].copy()

print("normalized rows:", len(reddit_df))
reddit_df.head()

normalized rows: 515

,source_item_key,post_id,comment_id,record_type,subreddit,author,title,text,permalink,url,created_utc_iso,scraped_at_iso,parent_id,parent_type,source_file
0,1s2hkj6_post,1s2hkj6,NaN,post,icecoast,Axe_S,Suggestion on Sunday River Trip for this weekend,,https://www.reddit.com/r/icecoast/comments/1s2...,/r/icecoast/comments/1s2hkd3/suggestion_on_sun...,2026-03-24T15:49:30Z,2026-03-24T18:29:45.933588Z,NaN,NaN,dataset_reddit-scraper_2026-03-24_18-29-51-236...
1,1s2hkd3_post,1s2hkd3,NaN,post,icecoast,Axe_S,Suggestion on Sunday River Trip for this weekend,"Hi everyone,\n\n \nI saw the great snow happe...",https://www.reddit.com/r/icecoast/comments/1s2...,https://old.reddit.com/r/icecoast/comments/1s2...,2026-03-24T15:49:19Z,2026-03-24T18:29:45.933860Z,NaN,NaN,dataset_reddit-scraper_2026-03-24_18-29-51-236...
2,1s2dqbl_post,1s2dqbl,NaN,post,icecoast,Smacpats111111,Any reports from Sunday River today or yesterday?,Trying to decide Sunday River vs Sugarloaf for...,https://www.reddit.com/r/icecoast/comments/1s2...,https://old.reddit.com/r/icecoast/comments/1s2...,2026-03-24T13:26:16Z,2026-03-24T18:29:45.933887Z,NaN,NaN,dataset_reddit-scraper_2026-03-24_18-29-51-236...
3,1s1vxim_post,1s1vxim,NaN,post,icecoast,sage89,Sunday River Conditions 3/23,Only skied for the last hour today. Groomed/pa...,https://www.reddit.com/r/icecoast/comments/1s1...,https://i.redd.it/fxlflfg9gvqg1.jpeg,2026-03-23T22:33:45Z,2026-03-24T18:29:45.933910Z,NaN,NaN,dataset_reddit-scraper_2026-03-24_18-29-51-236...
4,1s1f240_post,1s1f240,NaN,post,icecoast,astrobrite_,Sugarloaf and Sunday river worth the 6 hour dr...,Will sugarloaf open more terrain by Tuesday? I...,https://www.reddit.com/r/icecoast/comments/1s1...,https://old.reddit.com/r/icecoast/comments/1s1...,2026-03-23T12:08:51Z,2026-03-24T18:29:45.933930Z,NaN,NaN,dataset_reddit-scraper_2026-03-24_18-29-51-236...

In [15]:
print("rows before within-batch dedup:", len(reddit_df))

dup_mask = reddit_df.duplicated(subset=["source_item_key"], keep=False)
dup_rows = reddit_df[dup_mask].sort_values(["source_item_key"])

print("duplicated rows inside this batch:", len(dup_rows))
print("duplicated keys inside this batch:", dup_rows["source_item_key"].nunique())

reddit_dedup = reddit_df.drop_duplicates(subset=["source_item_key"]).reset_index(drop=True)

print("rows after within-batch dedup:", len(reddit_dedup))

rows before within-batch dedup: 515
duplicated rows inside this batch: 0
duplicated keys inside this batch: 0
rows after within-batch dedup: 515

In [16]:
def build_labeling_text(row: pd.Series) -> str:
    title = row["title"] if pd.notna(row["title"]) else ""
    text = row["text"] if pd.notna(row["text"]) else ""

    return (
        f"POST TITLE:\n{title}\n\n"
        f"REDDIT TEXT:\n{text}\n\n"
        f"CREATED UTC:\n{row['created_utc_iso']}"
    )

reddit_dedup["labeling_text"] = reddit_dedup.apply(build_labeling_text, axis=1)

reddit_dedup[
    ["source_item_key", "record_type", "labeling_text"]
].head(3)

,source_item_key,record_type,labeling_text
0,1s2hkj6_post,post,POST TITLE:\nSuggestion on Sunday River Trip f...
1,1s2hkd3_post,post,POST TITLE:\nSuggestion on Sunday River Trip f...
2,1s2dqbl_post,post,POST TITLE:\nAny reports from Sunday River tod...

Check on DB for dedup

In [17]:
import psycopg2
import pandas as pd

conn = psycopg2.connect(
    host="localhost",
    port=5432,
    dbname="ski_pipeline",
    user="airflow",
    password="airflow",
)

query = "SELECT source_item_key FROM reddit_labeled;"

existing_keys_df = pd.read_sql(query, conn)
conn.close()

existing_keys = set(existing_keys_df["source_item_key"].dropna())

print("existing labeled keys in postgres:", len(existing_keys))
print("rows in current batch:", len(reddit_df))

reddit_new = reddit_df[~reddit_df["source_item_key"].isin(existing_keys)].copy()

print("new rows to label:", len(reddit_new))
print("rows skipped as already labeled:", len(reddit_df) - len(reddit_new))

existing labeled keys in postgres: 0
rows in current batch: 515
new rows to label: 515
rows skipped as already labeled: 0

/var/folders/cx/wzprjdfn7xb7kgvmq3b_8nw80000gn/T/ipykernel_55685/2276304915.py:14: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  existing_keys_df = pd.read_sql(query, conn)

In [18]:
%pip install -q langchain-mistralai python-dotenv

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [19]:
import os
from pathlib import Path
from dotenv import load_dotenv

# Notebook is in reddit_data/, while .env is in project root
project_root = Path.cwd().parent
env_path = project_root / ".env"

load_dotenv(env_path)

mistral_api_key = os.getenv("MISTRAL_API_KEY")
if not mistral_api_key:
    raise ValueError(f"MISTRAL_API_KEY not found in {env_path}")

print("Loaded .env from:", env_path)
print("MISTRAL_API_KEY loaded:", bool(mistral_api_key))

Loaded .env from: /Users/nicholasnehemia/Documents/capstoneAirflow/.env
MISTRAL_API_KEY loaded: True

In [20]:
from typing import Optional, Literal
from pydantic import BaseModel, Field

class RedditLabel(BaseModel):
    report_type: Literal["field_report", "forecast_opinion", "other"] = Field(
        description="Whether this Reddit item describes actual observed ski conditions, expected upcoming conditions, or neither."
    )
    resort: Optional[Literal[
        "Loon",
        "SundayRiver",
        "Sugarloaf",
        "Killington",
        "Pico",
        "Sugarbush",
        "Stratton"
    ]] = Field(
        default=None,
        description="The ski resort being discussed. Null if unknown."
    )
    resolved_date: Optional[str] = Field(
        default=None,
        description="The ski day being discussed in YYYY-MM-DD format, or null if unknown."
    )
    date_resolution_source: Literal[
        "explicit_text",
        "relative_text",
        "fallback_post_date",
        "unknown"
    ] = Field(
        description="How the date was resolved."
    )
    sentiment_label: Literal["positive", "negative", "neutral"] = Field(
        description="Overall sentiment about ski conditions."
    )

In [21]:
from langchain_core.prompts import ChatPromptTemplate

prompt = ChatPromptTemplate.from_messages([
    (
        "system",
        """
You are labeling Reddit posts and comments about ski conditions.

Return a structured result with:
- report_type
- resort
- resolved_date
- date_resolution_source
- sentiment_label

Definitions:
- field_report: describes actual experienced or observed ski conditions on a real ski day
- forecast_opinion: discusses expected or upcoming ski conditions
- other: not a useful ski-conditions signal

Resort rules:
- Only choose from:
  Loon, SundayRiver, Sugarloaf, Killington, Pico, Sugarbush, Stratton
- Use text first, then title
- Do not guess without evidence

Date rules:
- resolved_date should be the ski day being discussed
- Use explicit dates first
- Use relative expressions like today, yesterday, tomorrow, this weekend relative to the created timestamp
- For field_report with no explicit or relative date, use fallback_post_date
- For forecast_opinion with vague timing and no clear date, return null and use unknown

Sentiment rules:
- positive = conditions described favorably
- negative = conditions described unfavorably
- neutral = mixed, unclear, or not really about conditions

Important:
- Judge ski conditions only, not unrelated tone
- Be conservative
        """.strip()
    ),
    (
        "human",
        """
Created timestamp: {created_utc_iso}

Post title:
{title}

Reddit text:
{text}
        """.strip()
    )
])

Langchain Prompting to label dataset

In [22]:
from langchain_mistralai import ChatMistralAI

llm = ChatMistralAI(
    model="mistral-large-latest",
    temperature=0,
    api_key=mistral_api_key,
)

structured_llm = llm.with_structured_output(RedditLabel)
chain = prompt | structured_llm

In [23]:
import pandas as pd

sample_df = reddit_new.head(10).copy()

sample_labels = []

for _, row in sample_df.iterrows():
    result = chain.invoke({
        "created_utc_iso": row["created_utc_iso"],
        "title": row["title"] if pd.notna(row["title"]) else "",
        "text": row["text"] if pd.notna(row["text"]) else "",
    })

    sample_labels.append({
        "source_item_key": row["source_item_key"],
        "report_type": result.report_type,
        "resort": result.resort,
        "resolved_date": result.resolved_date,
        "date_resolution_source": result.date_resolution_source,
        "sentiment_label": result.sentiment_label,
    })

sample_labels_df = pd.DataFrame(sample_labels)
sample_labels_df

,source_item_key,report_type,resort,resolved_date,date_resolution_source,sentiment_label
0,1s2hkj6_post,forecast_opinion,SundayRiver,2026-03-28,relative_text,neutral
1,1s2hkd3_post,forecast_opinion,SundayRiver,2026-03-28,relative_text,neutral
2,1s2dqbl_post,field_report,SundayRiver,2026-03-24,relative_text,neutral
3,1s1vxim_post,field_report,SundayRiver,2026-03-23,explicit_text,neutral
4,1s1f240_post,forecast_opinion,Sugarloaf,2026-03-24,relative_text,neutral
5,1s11ob9_post,field_report,SundayRiver,2026-03-23,fallback_post_date,positive
6,1s05x7t_post,field_report,SundayRiver,2026-03-21,explicit_text,positive
7,1rxyuhn_post,other,NaN,NaN,unknown,neutral
8,1rxlql4_post,forecast_opinion,NaN,2026-03-20,explicit_text,neutral
9,1rxi12h_post,other,NaN,NaN,unknown,neutral

REview samples to see if good or not

In [24]:
sample_review = sample_df.merge(sample_labels_df, on="source_item_key", how="left")

display(
    sample_review[
        [
            "source_item_key",
            "record_type",
            "created_utc_iso",
            "title",
            "text",
            "report_type",
            "resort",
            "resolved_date",
            "date_resolution_source",
            "sentiment_label",
        ]
    ]
)

,source_item_key,record_type,created_utc_iso,title,text,report_type,resort,resolved_date,date_resolution_source,sentiment_label
0,1s2hkj6_post,post,2026-03-24T15:49:30Z,Suggestion on Sunday River Trip for this weekend,,forecast_opinion,SundayRiver,2026-03-28,relative_text,neutral
1,1s2hkd3_post,post,2026-03-24T15:49:19Z,Suggestion on Sunday River Trip for this weekend,"Hi everyone,\n\n \nI saw the great snow happe...",forecast_opinion,SundayRiver,2026-03-28,relative_text,neutral
2,1s2dqbl_post,post,2026-03-24T13:26:16Z,Any reports from Sunday River today or yesterday?,Trying to decide Sunday River vs Sugarloaf for...,field_report,SundayRiver,2026-03-24,relative_text,neutral
3,1s1vxim_post,post,2026-03-23T22:33:45Z,Sunday River Conditions 3/23,Only skied for the last hour today. Groomed/pa...,field_report,SundayRiver,2026-03-23,explicit_text,neutral
4,1s1f240_post,post,2026-03-23T12:08:51Z,Sugarloaf and Sunday river worth the 6 hour dr...,Will sugarloaf open more terrain by Tuesday? I...,forecast_opinion,Sugarloaf,2026-03-24,relative_text,neutral
5,1s11ob9_post,post,2026-03-23T00:05:50Z,Sunday River won the day,Tons of fresh snow. Tons of terrain reopened.\...,field_report,SundayRiver,2026-03-23,fallback_post_date,positive
6,1s05x7t_post,post,2026-03-21T23:21:45Z,Sunday rivah conditions 3/21,"was great from 8-11am, spots felt deeper than ...",field_report,SundayRiver,2026-03-21,explicit_text,positive
7,1rxyuhn_post,post,2026-03-19T12:17:25Z,Mad River Glen,I have one ticket for Mad River Glen that can ...,other,NaN,NaN,unknown,neutral
8,1rxlql4_post,post,2026-03-19T00:38:10Z,"Crowds, vibes, conditions: Friday/Saturday: Bl...",I'm skiing Friday and Saturday and from where ...,forecast_opinion,NaN,2026-03-20,explicit_text,neutral
9,1rxi12h_post,post,2026-03-18T22:10:43Z,2025-2026 Projected Closing Dates,I summarized a list of U.S. Northeast mountain...,other,NaN,NaN,unknown,neutral

Label Full batch

In [25]:
labeled_rows = []

for _, row in reddit_new.iterrows():
    result = chain.invoke({
        "created_utc_iso": row["created_utc_iso"],
        "title": row["title"] if pd.notna(row["title"]) else "",
        "text": row["text"] if pd.notna(row["text"]) else "",
    })

    labeled_rows.append({
        "source_item_key": row["source_item_key"],
        "report_type": result.report_type,
        "resort": result.resort,
        "resolved_date": result.resolved_date,
        "date_resolution_source": result.date_resolution_source,
        "sentiment_label": result.sentiment_label,
    })

labels_df = pd.DataFrame(labeled_rows)
print("labeled rows:", len(labels_df))
labels_df.head()

labeled rows: 515

,source_item_key,report_type,resort,resolved_date,date_resolution_source,sentiment_label
0,1s2hkj6_post,forecast_opinion,SundayRiver,2026-03-28,relative_text,neutral
1,1s2hkd3_post,forecast_opinion,SundayRiver,2026-03-28,relative_text,neutral
2,1s2dqbl_post,field_report,SundayRiver,2026-03-24,relative_text,neutral
3,1s1vxim_post,field_report,SundayRiver,2026-03-23,explicit_text,neutral
4,1s1f240_post,forecast_opinion,NaN,NaN,unknown,neutral

Merge back into Full batch

In [30]:
from datetime import datetime, timezone

reddit_labeled_df = reddit_new.merge(labels_df, on="source_item_key", how="left")
reddit_labeled_df["labeling_model"] = "mistral-large-latest"
reddit_labeled_df["labeled_at"] = datetime.now(timezone.utc)

reddit_labeled_df = reddit_labeled_df[
    [
        "source_item_key",
        "post_id",
        "comment_id",
        "record_type",
        "subreddit",
        "author",
        "title",
        "text",
        "permalink",
        "url",
        "created_utc_iso",
        "scraped_at_iso",
        "report_type",
        "resort",
        "resolved_date",
        "date_resolution_source",
        "sentiment_label",
        "labeling_model",
        "labeled_at",
    ]
].copy()

reddit_labeled_df.head()

,source_item_key,post_id,comment_id,record_type,subreddit,author,title,text,permalink,url,created_utc_iso,scraped_at_iso,report_type,resort,resolved_date,date_resolution_source,sentiment_label,labeling_model,labeled_at
0,1s2hkj6_post,1s2hkj6,NaN,post,icecoast,Axe_S,Suggestion on Sunday River Trip for this weekend,,https://www.reddit.com/r/icecoast/comments/1s2...,/r/icecoast/comments/1s2hkd3/suggestion_on_sun...,2026-03-24T15:49:30Z,2026-03-24T18:29:45.933588Z,forecast_opinion,SundayRiver,2026-03-28,relative_text,neutral,mistral-large-latest,2026-03-29 16:43:12.196497+00:00
1,1s2hkd3_post,1s2hkd3,NaN,post,icecoast,Axe_S,Suggestion on Sunday River Trip for this weekend,"Hi everyone,\n\n \nI saw the great snow happe...",https://www.reddit.com/r/icecoast/comments/1s2...,https://old.reddit.com/r/icecoast/comments/1s2...,2026-03-24T15:49:19Z,2026-03-24T18:29:45.933860Z,forecast_opinion,SundayRiver,2026-03-28,relative_text,neutral,mistral-large-latest,2026-03-29 16:43:12.196497+00:00
2,1s2dqbl_post,1s2dqbl,NaN,post,icecoast,Smacpats111111,Any reports from Sunday River today or yesterday?,Trying to decide Sunday River vs Sugarloaf for...,https://www.reddit.com/r/icecoast/comments/1s2...,https://old.reddit.com/r/icecoast/comments/1s2...,2026-03-24T13:26:16Z,2026-03-24T18:29:45.933887Z,field_report,SundayRiver,2026-03-24,relative_text,neutral,mistral-large-latest,2026-03-29 16:43:12.196497+00:00
3,1s1vxim_post,1s1vxim,NaN,post,icecoast,sage89,Sunday River Conditions 3/23,Only skied for the last hour today. Groomed/pa...,https://www.reddit.com/r/icecoast/comments/1s1...,https://i.redd.it/fxlflfg9gvqg1.jpeg,2026-03-23T22:33:45Z,2026-03-24T18:29:45.933910Z,field_report,SundayRiver,2026-03-23,explicit_text,neutral,mistral-large-latest,2026-03-29 16:43:12.196497+00:00
4,1s1f240_post,1s1f240,NaN,post,icecoast,astrobrite_,Sugarloaf and Sunday river worth the 6 hour dr...,Will sugarloaf open more terrain by Tuesday? I...,https://www.reddit.com/r/icecoast/comments/1s1...,https://old.reddit.com/r/icecoast/comments/1s1...,2026-03-23T12:08:51Z,2026-03-24T18:29:45.933930Z,forecast_opinion,NaN,NaN,unknown,neutral,mistral-large-latest,2026-03-29 16:43:12.196497+00:00

In [31]:
print(reddit_labeled_df["report_type"].value_counts(dropna=False))
print(reddit_labeled_df["resort"].value_counts(dropna=False))
print(reddit_labeled_df["sentiment_label"].value_counts(dropna=False))

report_type
other               285
field_report        132
forecast_opinion     98
Name: count, dtype: int64
resort
NaN            395
SundayRiver     37
Sugarloaf       30
Killington      21
Sugarbush       16
Loon             9
Pico             4
Stratton         3
Name: count, dtype: int64
sentiment_label
neutral     383
positive     88
negative     44
Name: count, dtype: int64

In [32]:
import psycopg2
from psycopg2.extras import execute_values

def upsert_reddit_labeled(df: pd.DataFrame):
    if df.empty:
        print("No labeled reddit rows to insert.")
        return

    conn = psycopg2.connect(
        host="localhost",
        port=5432,
        dbname="ski_pipeline",
        user="airflow",
        password="airflow",
    )
    conn.autocommit = False

    sql = """
    INSERT INTO reddit_labeled (
        source_item_key,
        post_id,
        comment_id,
        record_type,
        subreddit,
        author,
        title,
        text,
        permalink,
        url,
        created_utc_iso,
        scraped_at_iso,
        report_type,
        resort,
        resolved_date,
        date_resolution_source,
        sentiment_label,
        labeling_model,
        labeled_at
    )
    VALUES %s
    ON CONFLICT (source_item_key)
    DO NOTHING;
    """

    values = [
        (
            row["source_item_key"],
            row["post_id"],
            row["comment_id"],
            row["record_type"],
            row["subreddit"],
            row["author"],
            row["title"],
            row["text"],
            row["permalink"],
            row["url"],
            pd.to_datetime(row["created_utc_iso"]).to_pydatetime() if pd.notna(row["created_utc_iso"]) else None,
            pd.to_datetime(row["scraped_at_iso"]).to_pydatetime() if pd.notna(row["scraped_at_iso"]) else None,
            row["report_type"],
            row["resort"],
            pd.to_datetime(row["resolved_date"]).date() if pd.notna(row["resolved_date"]) and row["resolved_date"] else None,
            row["date_resolution_source"],
            row["sentiment_label"],
            row["labeling_model"],
            pd.to_datetime(row["labeled_at"]).to_pydatetime() if pd.notna(row["labeled_at"]) else None,
        )
        for _, row in df.iterrows()
    ]

    try:
        with conn.cursor() as cur:
            execute_values(cur, sql, values, page_size=200)
        conn.commit()
        print(f"Inserted {len(values)} labeled reddit rows.")
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()

In [33]:
upsert_reddit_labeled(reddit_labeled_df)

Inserted 515 labeled reddit rows.

In [34]:
valid_df = reddit_labeled_df[
    (reddit_labeled_df["report_type"] != "other") &
    (reddit_labeled_df["resort"].notna()) &
    (reddit_labeled_df["resolved_date"].notna())
].copy()

In [35]:
sentiment_map = {
    "positive": 1,
    "negative": -1,
    "neutral": 0,
}

valid_df["sentiment_score"] = valid_df["sentiment_label"].map(sentiment_map)

In [36]:
report_weight_map = {
    "field_report": 2,
    "forecast_opinion": 1,
}

valid_df["report_weight"] = valid_df["report_type"].map(report_weight_map)

In [37]:
valid_df["weighted_contribution"] = (
    valid_df["sentiment_score"] * valid_df["report_weight"]
)

In [38]:
agg_df = (
    valid_df.groupby(["resort", "resolved_date"], as_index=False)
    .agg(
        field_report_count=("report_type", lambda s: (s == "field_report").sum()),
        forecast_opinion_count=("report_type", lambda s: (s == "forecast_opinion").sum()),
        positive_count=("sentiment_label", lambda s: (s == "positive").sum()),
        negative_count=("sentiment_label", lambda s: (s == "negative").sum()),
        neutral_count=("sentiment_label", lambda s: (s == "neutral").sum()),
        net_sentiment=("sentiment_score", "sum"),
        weighted_signal_score=("weighted_contribution", "sum"),
    )
    .rename(columns={"resolved_date": "ski_date"})
)

In [40]:
from datetime import datetime, timezone

agg_df["signal_present"] = 1
agg_df["updated_at"] = datetime.now(timezone.utc)

In [41]:
agg_df.head(20)

,resort,ski_date,field_report_count,forecast_opinion_count,positive_count,negative_count,neutral_count,net_sentiment,weighted_signal_score,signal_present,updated_at
0,Killington,2026-02-24,1,0,0,0,1,0,0,1,2026-03-29 16:44:56.944032+00:00
1,Killington,2026-02-28,0,2,0,0,2,0,0,1,2026-03-29 16:44:56.944032+00:00
2,Killington,2026-03-01,1,0,1,0,0,1,2,1,2026-03-29 16:44:56.944032+00:00
3,Killington,2026-03-06,0,1,0,0,1,0,0,1,2026-03-29 16:44:56.944032+00:00
4,Killington,2026-03-12,1,0,0,1,0,-1,-2,1,2026-03-29 16:44:56.944032+00:00
5,Killington,2026-03-14,3,0,3,0,0,3,6,1,2026-03-29 16:44:56.944032+00:00
6,Killington,2026-03-15,1,0,1,0,0,1,2,1,2026-03-29 16:44:56.944032+00:00
7,Killington,2026-03-21,1,0,1,0,0,1,2,1,2026-03-29 16:44:56.944032+00:00
8,Killington,2026-04-01,1,0,1,0,0,1,2,1,2026-03-29 16:44:56.944032+00:00
9,Killington,2026-05-01,1,0,1,0,0,1,2,1,2026-03-29 16:44:56.944032+00:00
10,Loon,2026-03-10,1,0,0,0,1,0,0,1,2026-03-29 16:44:56.944032+00:00
11,Loon,2026-03-14,1,0,1,0,0,1,2,1,2026-03-29 16:44:56.944032+00:00
12,Loon,2026-03-17,1,0,0,0,1,0,0,1,2026-03-29 16:44:56.944032+00:00
13,Loon,2026-03-18,1,0,0,1,0,-1,-2,1,2026-03-29 16:44:56.944032+00:00
14,Loon,2026-03-19,0,1,0,0,1,0,0,1,2026-03-29 16:44:56.944032+00:00
15,Loon,2026-03-21,0,1,0,1,0,-1,-1,1,2026-03-29 16:44:56.944032+00:00
16,Pico,2026-02-21,1,0,1,0,0,1,2,1,2026-03-29 16:44:56.944032+00:00
17,Pico,2026-02-23,2,0,2,0,0,2,4,1,2026-03-29 16:44:56.944032+00:00
18,Stratton,2026-03-15,1,0,1,0,0,1,2,1,2026-03-29 16:44:56.944032+00:00
19,Stratton,2026-03-16,1,0,0,1,0,-1,-2,1,2026-03-29 16:44:56.944032+00:00

Insert Data into Table

In [57]:
import psycopg2
import os
from dotenv import load_dotenv

load_dotenv()

conn = psycopg2.connect(
    host="localhost",
    port=5432,
    dbname="ski_pipeline",   # 🔥 THIS must match DBeaver
    user="airflow",
    password="airflow",
)

cur = conn.cursor()

In [58]:
cur.execute("SELECT current_database();")
print(cur.fetchone())

('ski_pipeline',)

In [59]:
insert_query = """
INSERT INTO reddit_resort_day_signals (
    resort,
    ski_date,
    field_report_count,
    forecast_opinion_count,
    positive_count,
    negative_count,
    neutral_count,
    net_sentiment,
    weighted_signal_score,
    signal_present,
    updated_at
)
VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
ON CONFLICT (resort, ski_date)
DO UPDATE SET
    field_report_count = EXCLUDED.field_report_count,
    forecast_opinion_count = EXCLUDED.forecast_opinion_count,
    positive_count = EXCLUDED.positive_count,
    negative_count = EXCLUDED.negative_count,
    neutral_count = EXCLUDED.neutral_count,
    net_sentiment = EXCLUDED.net_sentiment,
    weighted_signal_score = EXCLUDED.weighted_signal_score,
    signal_present = EXCLUDED.signal_present,
    updated_at = EXCLUDED.updated_at;
"""

In [60]:
from tqdm import tqdm

rows = []

for _, r in agg_df.iterrows():
    rows.append((
        r["resort"],
        r["ski_date"],
        int(r["field_report_count"]),
        int(r["forecast_opinion_count"]),
        int(r["positive_count"]),
        int(r["negative_count"]),
        int(r["neutral_count"]),
        int(r["net_sentiment"]),
        int(r["weighted_signal_score"]),
        int(r["signal_present"]),
        r["updated_at"],
    ))

print(f"Inserting {len(rows)} rows...")

for row in tqdm(rows):
    cur.execute(insert_query, row)

conn.commit()
cur.close()
conn.close()

print("✅ Reddit aggregated signals loaded")

Inserting 52 rows...

100%|██████████| 52/52 [00:00<00:00, 895.52it/s]

✅ Reddit aggregated signals loaded